version: '3.8'
services:
  auto-db:
    image: postgres
    container_name: book_db
    environment:
      POSTGRES_DB: book_db
      POSTGRES_USER: service
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
